# -*- coding: utf-8 -*-
"""Calculating Technical Indicators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdo_upQ5sLrQzQ-HtZmiK98sqEix3pn8
"""

from google.colab import files
import pandas as pd
import numpy as np

uploaded = files.upload()
file_name = next(iter(uploaded))
df = pd.read_csv(file_name)

#calc macd's
def macd(df, fastperiod=12, slowperiod=26, signalperiod=9):
    # EMAs
    df['EMA_Fast'] = df['Close'].ewm(span=fastperiod, adjust=False).mean()
    df['EMA_Slow'] = df['Close'].ewm(span=slowperiod, adjust=False).mean()

    # MACD = EMA Fast - EMA Slow
    df['MACD'] = df['EMA_Fast'] - df['EMA_Slow']

    # Signal of MacD
    df['Signal'] = df['MACD'].ewm(span=signalperiod, adjust=False).mean()

    # MACD - Signal
    df['MACD_Histogram_Val'] = df['MACD'] - df['Signal']

    return df

#calc rsi
def rsi(df, period=14):
#so on



df = macd(df)
output_file_name = f' {file_name[:-3]}withIndicators.csv'
df.to_csv(output_file_name, index=False)

# Download the CSV file
files.download(output_file_name)